{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1", "trace": "self = <test_price1.Test object at 0x7f9c023d0890>\n\n    @allure.feature('huodhuwdhi')\n    @allure.story('denglushibai')\n    def test_fail(self):\n>       assert 2 == 1\nE       assert 2 == 1\n\ncases/test_price1.py:24: AssertionError"}, "start": 1620833440205, "stop": 1620833440206, "uuid": "bc8da290-bf81-46b4-a9e8-b7399c767ebc", "historyId": "2572641e4810943100c95b6256e630ac", "testCaseId": "0da9d6af3d08040be4beece6f392b81b", "fullName": "cases.test_price1.Test#test_fail", "labels": [{"name": "feature", "value": "huodhuwdhi"}, {"name": "story", "value": "denglushibai"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_price1"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "192.168.0.102"}, {"name": "thread", "value": "45669-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_price1"}]}