{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1", "trace": "self = <test_price1.Test object at 0x7f85614e19d0>\n\n    @allure.feature('huodhuwdhi')\n    @allure.story('denglushibai')\n    def test_fail(self):\n>       assert 2 == 1\nE       assert 2 == 1\n\ncases/test_price1.py:24: AssertionError"}, "start": 1620834811026, "stop": 1620834811026, "uuid": "57bc95f5-ccae-4cb2-8768-047edcbc4682", "historyId": "2572641e4810943100c95b6256e630ac", "testCaseId": "0da9d6af3d08040be4beece6f392b81b", "fullName": "cases.test_price1.Test#test_fail", "labels": [{"name": "story", "value": "denglushibai"}, {"name": "feature", "value": "huodhuwdhi"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_price1"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "192.168.0.102"}, {"name": "thread", "value": "46105-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_price1"}]}